### ISSUE TITLE
能否将事件全部暴露出来？

### ISSUE THREAD

**Issue by ZhaoYu8** [caohuatao/vue-super-flow#12]
比如说，节点移动结束。全选移动结束，右键选中节点。选中连线等等

**Comment by Ychuoso** [comment]
对的，还有节点点击

**Comment by martinwithyou** [comment]
我改了作者的源码，
将操作节点的事件，
全都暴露出来了，
譬如remove

**Comment by ZhaoYu8** [comment]
> 我改了作者的源码，
> 将操作
> 例程的事件，全都暴露出来了，例如
> 删除

我也改了，但后来需求disable能解决很多事情。我又撤销了。

**Comment by martinwithyou** [comment]
> 对的，还有节点点击

我都是自己增加事件，

对于节点的单击事件，
对于节点的双击事件，
对于线条的单击事件，
对于线条的双击事件，
选择节点事件，
hover节点事件，
选中节点事件，‘
按键盘删除节点

**Comment by dongaifeng** [comment]
slot里面添加点击事件第一次点击不触发，怎么回事？

**Comment by caohuatao** [comment]
触发聚焦。你需要阻止事件冒泡

**Comment by martinwithyou** [comment]
> slot里面添加点击事件第一次点击不触发，怎么回事？

在slot 里面，
点击事件是没有问题的，
看看是不是你的代码问题，
多做一些对照demo，
加油吧

**Comment by windeyes** [comment]
> slot里面添加点击事件第一次点击不触发，怎么回事？

我也遇到这个问题，你需要在package里面修改node.vue的nodeMousedown事件，我把他在graph中的操作给注释了，然后发现可以用，暂时不知道根本原因，但如果你急的话可以试下
