### ISSUE TITLE
可以设置 图片不能拖出边界嘛？

### ISSUE THREAD

**Issue by martinwithyou** [caohuatao/vue-super-flow#16]
可以设置 图片不能拖出边界嘛？

**Comment by caohuatao** [comment]
是节点吗？是可以自行修改判断限制的。

**Comment by martinwithyou** [comment]
不是节点，是整体拖移发自我的iPhone------------------ 原始邮件 ------------------发件人: notifications@github.com <notifications@github.com>发送时间: 2020年9月9日 10:01收件人: caohuatao/vue-super-flow <vue-super-flow@noreply.github.com>抄送: 嵇德竹 <smartmartin@163.com>, Author <author@noreply.github.com>主题: 回复：[caohuatao/vue-super-flow] 可以设置 图片不能拖出边界嘛？ (#16)
是节点吗？是可以自行修改判断限制的。

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/caohuatao/vue-super-flow/issues/16#issuecomment-689251717",
"url": "https://github.com/caohuatao/vue-super-flow/issues/16#issuecomment-689251717",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by martinwithyou** [comment]
> 是节点吗？是可以自行修改判断限制的。

整体的流程图拖移，

可以不让它移出画布的，

可是区域嘛？

**Comment by caohuatao** [comment]
内部是没有直接提供限制的方法。

**Comment by caohuatao** [comment]
内部没有提供直接限制的逻辑

```
moveWhole(evt) {
        if (this.moveAllConf.isMove) {
          const offset = vector(this.moveAllConf.downPosition)
            .differ([evt.clientX, evt.clientY])
            .end
          arrayReplace(
            this.graph.origin,
            vector(this.moveAllConf.origin)
              .add(offset)
              .end
          )
        }
      }
```

这是内部在触发拖动时更新 graph origin 坐标。你可以在这里加入判断

**Comment by caohuatao** [comment]
arrayReplace 是将数组原地替换

**Comment by martinwithyou** [comment]
好吧，我有空试一下，这两天比较忙，
谢谢你哦，
you are so nice,
thank you....

**Comment by liuyingqq123** [comment]
发现往上边缘拖拽, 和往左边缘拖拽, 都会拖出可视范围, 而不会自动加滚动条, 往右和往下没问题. 请问有什么办法吗? 希望往上和左拖出边界, 自动加滚动条
