### ISSUE TITLE
双击线条的事件可以暴露出来嘛？

### ISSUE THREAD

**Issue by martinwithyou** [caohuatao/vue-super-flow#17]
双击线条的事件可以暴露出来嘛？

**Comment by martinwithyou** [comment]
双击线条事件，
我自己已经实现了，
就是方法有点“笨”，

**Comment by martinwithyou** [comment]
document.addEventListener('dblclick', this.onDocumenDblClick);

      onDocumenDblClick(event) {
        if(event.target.outerHTML.length < 300){
          if(event.target.outerHTML.indexOf('super-flow__line') > 0){
            this.drawerConf.open(drawerType.link, this.selectLine)
          }else{
            console.log("点击节点之上")
          }
        }
      },

**Comment by martinwithyou** [comment]
说白了，
就是根据 dom 的数据结构
来做判断

**Comment by caohuatao** [comment]
![image](https://user-images.githubusercontent.com/44050286/93288970-af737a00-f80f-11ea-87af-c30246040b58.png)

这是右键菜单事件，通过 this.graph.mouseonLink 是否存在以及当前鼠标是否在 link 设定范围内。

**Comment by caohuatao** [comment]
监听 doc 双击事件 触发时 使用 ‘graph.mouseonLink && graph.mouseonLink.isPointInLink(position)’ 判断触发时鼠标是否在线上   
然后调用对应逻辑就可以了

**Comment by caohuatao** [comment]
export function getOffset(evt, target = null) {
  const {
    clientX,
    clientY,
    currentTarget
  } = evt
  
  const current = target || currentTarget
  
  const {
    left,
    top
  } = current.getBoundingClientRect()
  
  return [clientX - left, clientY - top]
}


这个函数是内部获取 position 的逻辑

**Comment by caohuatao** [comment]
详细 需要参考内部右键事件
contextmenu(evt) {
        const mouseonLink = this.graph.mouseonLink
        const position = getOffset(evt)
        let list, source

        if (mouseonLink && mouseonLink.isPointInLink(position)) {
          list = this.initMenu(this.linkMenu, mouseonLink)
          source = mouseonLink
        } else {
          if (mouseonLink) this.graph.mouseonLink = null
          list = this.initMenu(this.graphMenu, this.graph)
          source = this.graph
        }

        this.showContextMenu(
          position,
          list,
          source
        )
      }

**Comment by caohuatao** [comment]
`
      contextmenu(evt) {
        const mouseonLink = this.graph.mouseonLink
        const position = getOffset(evt)
        let list, source

        if (mouseonLink && mouseonLink.isPointInLink(position)) {
          list = this.initMenu(this.linkMenu, mouseonLink)
          source = mouseonLink
        } else {
          if (mouseonLink) this.graph.mouseonLink = null
          list = this.initMenu(this.graphMenu, this.graph)
          source = this.graph
        }

        this.showContextMenu(
          position,
          list,
          source
        )
      }
`

**Comment by caohuatao** [comment]
可以参考内部右键菜单实现逻辑：


```
contextmenu(evt) {
        const mouseonLink = this.graph.mouseonLink
        const position = getOffset(evt)
        let list, source
        if (mouseonLink && mouseonLink.isPointInLink(position)) {
          list = this.initMenu(this.linkMenu, mouseonLink)
          source = mouseonLink
        } else {
          if (mouseonLink) this.graph.mouseonLink = null
          list = this.initMenu(this.graphMenu, this.graph)
          source = this.graph
        }
        this.showContextMenu(
          position,
          list,
          source
        )
     }
```
