### ISSUE TITLE
全选时， css 样式错乱

### ISSUE THREAD

**Issue by martinwithyou** [caohuatao/vue-super-flow#22]
dom会超出，
破坏原有布局

**Comment by ChainsDW** [comment]
你需要在渲染后调整外面div的高度和宽度，不然拖拽或者全选会乱

**Comment by martinwithyou** [comment]
> 你需要在渲染后调整外面div的高度和宽度，不然拖拽或者全选会乱

谢谢......

**Comment by caohuatao** [comment]
demo 和内部 css 只是供参考和部分便利！
目前我计划在下个大版本不再编写内部样式，只是提供一整套方案实现各种需求的流程图。
