### ISSUE TITLE
节点与节点之间的连接可以设置成某几条是虚线 某几条是实线 并且颜色自定义吗

### ISSUE THREAD

**Issue by SummerGC** [caohuatao/vue-super-flow#24]
如题

**Comment by SummerGC** [comment]
博主有在看这个需求吗 最近的项目可能用到博主这个插件 但是不知道能不能实现上述功能

**Comment by caohuatao** [comment]
![image](https://user-images.githubusercontent.com/44050286/94524160-cdf06100-0264-11eb-8b23-797f4fb1138d.png)
 请看文档
