### ISSUE TITLE
需要安装browserslist吗？我浏览器引入import 'vue-super-flow/lib/index.css'时报错了

### ISSUE THREAD

**Issue by eliya123** [caohuatao/vue-super-flow#25]
./node_modules/css-loader??ref--5-1!./node_modules/postcss-loader/lib??ref--5-2!./node_modules/vue-super-flow/lib/index.css
Module build failed: BrowserslistError: Unknown browser query `dead`
    at C:\webstorm\Fund\node_modules\autoprefixer\node_modules\browserslist\index.js:164:11
    at Array.reduce (<anonymous>)

**Comment by caohuatao** [comment]
package.json  
`
"browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ]

`

**Comment by caohuatao** [comment]
https://github.com/browserslist/browserslist/issues/266
