### ISSUE TITLE
能否通过json生成可视化流程图？

### ISSUE THREAD

**Issue by eliya123** [caohuatao/vue-super-flow#28]
能否通过类似如下的json生成可视化的流程图？
{
	"id": "00000",
	"meta": {
		"prop": "start",
		"name": "条件节点1"
	}
	children: [{
			"id": "11111",
			"meta": {
				"prop": "start",
				"name": "条件节点1"
			}
		},
		{
			"id": "22222",
			"meta": {
				"prop": "start",
				"name": "条件节点2"
			},
		},

	]
}

**Comment by martinwithyou** [comment]
> 能否通过类似如下的json生成可视化的流程图？
> {
> "id": "00000",
> "meta": {
> "prop": "start",
> "name": "条件节点1"
> }
> children: [{
> "id": "11111",
> "meta": {
> "prop": "start",
> "name": "条件节点1"
> }
> },
> {
> "id": "22222",
> "meta": {
> "prop": "start",
> "name": "条件节点2"
> },
> },
> 
> ```
> ]
> ```
> 
> }

可以的

**Comment by caohuatao** [comment]
上面展示的数据结构是属于 “树型数据结构”。
组件采用的是 “图数据结构”。
你需要将数据结构转换

**Comment by martinwithyou** [comment]
> 上面展示的数据结构是属于 “树型数据结构”。
> 组件采用的是 “图数据结构”。
> 你需要将数据结构转换
对的哦
