### ISSUE TITLE
建议修改下介绍

### ISSUE THREAD

**Issue by D1N910** [caohuatao/vue-super-flow#3]
vue flow components
->
vue-super-flow 是一款快速方便实现流程图的 vue 插件。Demo地址 ：https://caohuatao.github.io/demo/；
Vue-super-flow is a quick and convenient Vue plug-in to realize flow chart. Demo address: https://caohuatao.github.io/demo/ ;

**Comment by caohuatao** [comment]
好嘞！感谢
