### ISSUE TITLE
节点id是唯一的吗，我找了半天没看到生成id的函数

### ISSUE THREAD

**Issue by zzc69** [caohuatao/vue-super-flow#30]

**Comment by martinwithyou** [comment]
> _No description provided._

可以自定义节点的id

**Comment by zzc69** [comment]
> > _没有提供描述。_
> 
> 可以自定义分析师的id

文档上并没有啊

**Comment by martinwithyou** [comment]
> > > _没有提供描述。_
> > 
> > 
> > 可以自定义分析师的id
> 
> 文档上并没有啊

自己摸索一下。。。
这是一个很年轻的开源项目

**Comment by caohuatao** [comment]
最好使用自行生成唯一 id，或者使用后台生成唯一 id.生成 id 的函数可以查找 uuid 的生成方式 或者

**Comment by martinwithyou** [comment]
> 最好使用自行生成唯一 id，或者使用后台生成唯一 id.
> 生成 id 的函数可以查找 uuid 等生成唯一id方法。

我之前就是用math.random()这个函数，随机生成id
