### ISSUE TITLE
根据josn能生成图形吗？

### ISSUE THREAD

**Issue by lanvendar** [caohuatao/vue-super-flow#32]
直接把json赋值给this.$refs.superFlow.graph并不能展示

"origin": [
            0,
            0
          ],
          "nodeList": [
            {
              "id": "node43bEDxs4QYLxYqA8",
              "width": 120,
              "height": 40,
              "coordinate": [
                293.11109924316406,
                115.24305725097656
              ],
              "meta": {
                "nodeSn": "20201117155528475709",
                "nodeType": 12,
                "name": "swooptask222",
                "retryTimes": "2"
              }
            },
            {
              "id": "nodex3J2Ah7U3lf3ohnK",
              "width": 120,
              "height": 40,
              "coordinate": [
                214.11109924316406,
                212.24305725097656
              ],
              "meta": {
                "nodeType": 1,
                "processInfoSn": "20201118144643126323",
                "name": "qwe",
                "flag": 1,
                "isSubProcess": 1,
                "releaseState": 1,
                "processLevel": 1,
                "runStrategy": 2,
                "projectSn": "20201111151301378332",
                "hasEvent": 1
              }
            }
          ],
          "linkList": [
            {
              "id": "linkqUDpYBsyXW857ojR",
              "startId": "node43bEDxs4QYLxYqA8",
              "endId": "nodex3J2Ah7U3lf3ohnK",
              "startAt": [
                60,
                40
              ],
              "endAt": [
                120,
                20
              ],
              "meta": null
            }
          ]
        }

**Comment by lanvendar** [comment]
已解决有init方法

**Comment by SYH1503** [comment]
> 已解决有init方法
调用哪个init方法
