### ISSUE TITLE
readme 安装命令写错了

### ISSUE THREAD

**Issue by G-lory** [caohuatao/vue-super-flow#35]
`yarn add vue-spuer-flow`

readme和文档里都写错了，试了好几次都安装失败才发现=_=#

**Comment by caohuatao** [comment]
[#34 ](https://github.com/caohuatao/vue-super-flow/issues/34)

**Comment by G-lory** [comment]
> [#34 ](https://github.com/caohuatao/vue-super-flow/issues/34)

额 是 super 写成了 spuer

**Comment by caohuatao** [comment]
好的马上改
