### ISSUE TITLE
请问连接线支持编辑吗 比如希望在连接线上展示文字

### ISSUE THREAD

**Issue by YYzoneYY** [caohuatao/vue-super-flow#4]
项目有这个需求 但是没有发现插槽跟接口

**Comment by caohuatao** [comment]
连线上添加文字目前没有这功能，不过线对象可以自定义编辑操作并携带自定义数据。

**Comment by YYzoneYY** [comment]
那有开发这个功能的打算吗 找了很多流程图组件 目前感觉最合适的还是您写的这个 但是需求里需要在连线上展示文字 类似这种  如果不能的话 可能要去重新研究别的组件了 
![31711595041320_ pic](https://user-images.githubusercontent.com/37871074/87844037-93c12580-c8eb-11ea-8052-5aafc927fbe9.jpg)

**Comment by YYzoneYY** [comment]
![31711595041320_ pic](https://user-images.githubusercontent.com/37871074/87844054-b9e6c580-c8eb-11ea-8f84-2692fd29c5a8.jpg)

**Comment by caohuatao** [comment]
有这打算，不过时间比较少不确定完成时间。

**Comment by YYzoneYY** [comment]
好吧 打扰了
