### ISSUE TITLE
关于css引入的问题

### ISSUE THREAD

**Issue by yuanyuan1993** [caohuatao/vue-super-flow#43]
尊敬的大佬，您好，
请问一下
`Failed to compile.

./node_modules/css-loader??ref--5-1!./node_modules/postcss-loader/lib??ref--5-2!./node_modules/vue-super-flow/lib/index.css
Module build failed: BrowserslistError: Unknown browser query `dead``

请问这个是什么问题哈

**Comment by caohuatao** [comment]
package.json 中 browserslist 的配置

```json 
"browserslist": [
    "> 1%",
    "last 2 versions"
  ],
```
