### ISSUE TITLE
为什么修改一个节点的meta信息，同一类节点的都变了呢，怎么修改

### ISSUE THREAD

**Issue by liuyahui32** [caohuatao/vue-super-flow#46]

**Comment by lance-li** [comment]
![Uploading image.png…]()

**Comment by lance-li** [comment]
很明显 很基础的对象指针引用啊 ，内存

**Comment by lance-li** [comment]
![image](https://user-images.githubusercontent.com/21050392/114374608-6cfff900-9bb6-11eb-9a9f-3d46378b1c01.png)

**Comment by lance-li** [comment]
你代码 也不撸上，让别人猜你的问题啊
