### ISSUE TITLE
报错BrowserslistError: Unknown browser query `dead`

### ISSUE THREAD

**Issue by xiaojiezi77** [caohuatao/vue-super-flow#47]
![image](https://user-images.githubusercontent.com/54147894/114689024-dfeca980-9d47-11eb-92e5-49c68d6db2c9.png)

**Comment by caohuatao** [comment]
`https://github.com/browserslist/browserslist/issues/276`

**Comment by caohuatao** [comment]
[#276](https://github.com/browserslist/browserslist/issues/276)
