### ISSUE TITLE
大佬，加一个连线成功后的回调函数吧

### ISSUE THREAD

**Issue by xdlStrive** [caohuatao/vue-super-flow#50]
![image](https://user-images.githubusercontent.com/26785115/120510170-bec94080-c3fb-11eb-9467-0216e7e9ac67.png)
就在这个nodeMouseup方法里面加个callback就行，我有个需求，要在手动连线之后调用一个回调函数来完成一些操作，如果没有回调函数的话实在是不方便...

**Comment by caohuatao** [comment]
enterIntercept

**Comment by caohuatao** [comment]
连线进入限制函数 你自己可以在里面做逻辑

**Comment by zhyusgethup** [comment]
好的大佬
