### ISSUE TITLE
流程图在大屏上 节点的线条显示不完整或者不显示出来

### ISSUE THREAD

**Issue by HHL030303** [caohuatao/vue-super-flow#52]
在大屏上显示会存在问题  线条不能完整的显示  或者显示部分
![image](https://user-images.githubusercontent.com/22982892/122697656-5e9a2180-d278-11eb-9b09-61cbca76dec3.png)

**Comment by HHL030303** [comment]
有没有什么补救的方法 我这边需要在大屏上展示
我尝试过缩放  效果不是很好 还有其他方法吗

**Comment by caohuatao** [comment]
尝试下改代码将线条加粗。可能是像素和分辨率导致的！
