### ISSUE TITLE
出现这样的情况，一般是什么问题？

### ISSUE THREAD

**Issue by yang1366788** [caohuatao/vue-super-flow#58]
![image](https://user-images.githubusercontent.com/43667203/134706693-345a1bb8-433f-47ce-9b70-a5c628e4a835.png)
会不会是什么js或者css与vue-super-flow冲突了，但是我没有找到

**Comment by caohuatao** [comment]
引入 CSS 了吗？这个问题是应该CSS 没引入。

**Comment by yang1366788** [comment]
> 引入 CSS 这个问题是应该 CSS 没引入。
引入了css，其实就是把默认示例搬过来就这样
我新建一个项目，把默认示例搬过来没问题，但整合到公司项目就出现这样的问题，怀疑是css冲突，但又排查不出来，所以来问问看
