### ISSUE TITLE
两个节点之间的连线 可不可以 自定义拖动呀?

### ISSUE THREAD

**Issue by yzh0120** [caohuatao/vue-super-flow#59]
两个节点之间的连线 可不可以 自定义拖动呀?
有时候 连接线太多 会重叠在一起,如果能够对单独的连线 根据鼠标来拖动 就好了

**Comment by wocswang** [comment]
问你个问题，就是我把example中的例子放到项目中，报meta没定义，有遇到吗

**Comment by caohuatao** [comment]
可以的需要对源码小小修改下、原本是随意确定 startAt 和 endAt 后来觉得乱 就 合并到中间了。

**Comment by caohuatao** [comment]
example 中的例子应该是使用meta中的数据。需要修改下。

**Comment by yzh0120** [comment]
> 可以需要对源码小小修改下、本来是自愿确定开始在和结束在后来觉得乱就合并到中间了。

大佬 有联系方式 ?  我想请问大佬怎么修改
