### ISSUE TITLE
不使用右键 如何获取跟更改nodelist里的数据

### ISSUE THREAD

**Issue by YYzoneYY** [caohuatao/vue-super-flow#6]
nodelist不是双向绑定的 想在父组件中获取修改更新后的nodelist的数据 以及 如何修改nodelist中的数据传给子组件

**Comment by caohuatao** [comment]
nodeList 会在组件内部用来初始化 Graph 对象，你可以通过 Graph 对象的 nodeList 时时修改。

` console.log(this.$refs.superFlow.graph)`

![image](https://user-images.githubusercontent.com/44050286/88243740-fcc9e400-ccc3-11ea-8452-3acf73beef1f.png)


在后续文档中会对 Graph、GraphNode、GraphLink 结构以及方法进行详细说明。
