### ISSUE TITLE
请问大佬如何对源码小小修改 可以实现两个节点之间的连线可以自定义拖动

### ISSUE THREAD

**Issue by yzh0120** [caohuatao/vue-super-flow#60]
请问大佬如何对源码小小修改 可以实现两个节点之间的连线可以自定义拖动
如果可以的话 有qq等联系方式吗

**Comment by yzh0120** [comment]
我的qq是 3037666259

**Comment by yzh0120** [comment]
或者定个字段 来 配置是否开启 两个节点之间的连线是否可以自定义拖动

**Comment by caohuatao** [comment]
是可以从节点边的任意起点开始连线到另一个节点的边缘任意点么？

**Comment by yzh0120** [comment]
是的 如果节点太多  难免会有连线重叠,所以需要自定义拖动连线
