### ISSUE TITLE
单个节点添加背景图片

### ISSUE THREAD

**Issue by h03147** [caohuatao/vue-super-flow#70]
请问如何给单个节点添加背景图片
我这么写无效：
.super-flow__node {
            .flow-node {
                &.flow-node-start {
                    width: 70%;
                    height: 80px;
                    line-height: 50px;
                    background: url('../assets/common/image.jpeg') no-repeat;
                    border-radius: 60px;
                }
}
}

**Comment by caohuatao** [comment]
![image](https://user-images.githubusercontent.com/44050286/157598876-ea370843-08af-4427-9342-93f8af99ed3b.png)
检查下你的路径和代码。添加背景图是没有任何问题的

**Comment by h03147** [comment]
好的 谢谢大佬
