### ISSUE TITLE
demo中的meta undefined

### ISSUE THREAD

**Issue by NevynPeng** [caohuatao/vue-super-flow#72]
你好，小白一枚，将demo完整移到我的项目中启动后，报错meta undefined.
源自demo中
<template v-slot:node="{meta}">
   <div :class="`flow-node flow-node-${meta.prop}`">
        <header class="ellipsis">
             {{meta.name}}
        </header>
        <section>
             {{meta.desc}}
        </section>
   </div>
</template>

想请教一下代码中的meta是否需要自行更替成其他变量？或者是我引入的问题？

**Comment by NevynPeng** [comment]
```
<template v-slot:node="{meta}">
        <div :class="`flow-node flow-node-${meta.prop}`">
          <header class="ellipsis">
            {{ meta.name }}
          </header>
          <section>
            {{ meta.desc }}
          </section>
        </div>
      </template>
```

**Comment by caohuatao** [comment]
npm引入还是复制组件源码引入



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: NevynPeng ***@***.***&gt;
发送时间: 2022年4月11日 17:16
收件人: caohuatao/vue-super-flow ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [caohuatao/vue-super-flow] demo中的meta undefined (Issue #72)





 
你好，小白一枚，将demo完整移到我的项目中启动后，报错meta undefined.
 源自demo中
    
                       {{meta.name}}                                {{meta.desc}}             
 


想请教一下代码中的meta是否需要自行更替成其他变量？或者是我引入的问题？

**Comment by ushirogo** [comment]
> 你好，小白一枚，将demo完整移到我的项目中启动后，报错meta undefined. 源自demo中
> 
> {{meta.name}}
> {{meta.desc}}
> 想请教一下代码中的meta是否需要自行更替成其他变量？或者是我引入的问题？

我也出现了这个问题，最后是更换了vue版本解决的，你用的vue版本是多少

**Comment by NevynPeng** [comment]
我是npm install vue-super-flow的

**Comment by NevynPeng** [comment]
> > 你好，小白一枚，将demo完整移到我的项目中启动后，报错meta undefined. 源自demo中
> > {{meta.name}}
> > {{meta.desc}}
> > 想请教一下代码中的meta是否需要自行更替成其他变量？或者是我引入的问题？
> 
> 我也出现了这个问题，最后是更换了vue版本解决的，你用的vue版本是多少

更换vue版本就解决了么？我明天看下项目

**Comment by NevynPeng** [comment]
> > > > 你好，小白一枚，将demo完整移到我的项目中启动后，报错meta undefined. 源自demo中
> > > > {{meta.name}}
> > > > {{meta.desc}}
> > > > 想请教一下代码中的meta是否需要自行更替成其他变量？或者是我引入的问题？
> > > 
> > > 
> > > 我也出现了这个问题，最后是更换了vue版本解决的，你用的vue版本是多少
> > 
> > 
> > 更换vue版本就解决了么？我明天看下项目
> 
> 是的 从2.6开始支持的,我也是昨天偶然在官网看到的,我就换到2.6.0了

嗯确实是 2.6开始才支持插槽传参...哎可惜 项目不让升级...只能放弃super-flow了

**Comment by caohuatao** [comment]
2.6.0版本之前采用的是 slot="node"  slot-scope="{meta}" 的方式。

**Comment by caohuatao** [comment]
https://cn.vuejs.org/v2/api/#slot-scope-%E5%BA%9F%E5%BC%83

**Comment by NevynPeng** [comment]
> 

好的 十分感谢

> 2.6.0版本之前采用的是 slot="node" slot-scope="{meta}" 的方式。
