### ISSUE TITLE
有没有用CDN的版本，我们这不允许用NPM

### ISSUE THREAD

**Issue by ahjihyqw** [caohuatao/vue-super-flow#74]
如题

**Comment by caohuatao** [comment]
从 node_modules 中 找到 vueSuperFlow 里的 min.js 和 css 拷贝出来放到项目文件夹中引入即可

**Comment by MingMingDa** [comment]
为什么我这样引入只后组件没有生效
![image](https://github.com/caohuatao/vue-super-flow/assets/52748907/b47d8eca-178f-49f8-ba0b-a45f88b41530)

**Comment by MingMingDa** [comment]
为什么我引入之后组件没有生效
`<body>
  <div id="app">
    <div class="flow">
      <super-flow></super-flow>
    </div>
  </div>

  
  <script src="./static/lib/index.umd.min.js"></script>
  <link rel="stylesheet" href="./static/lib/index.css">
  <script>
    var vm = new Vue({
      el: '#app',
      component: { SuperFlo },
    })
  </script>
</body>`

**Comment by MingMingDa** [comment]
为什么我引入之后组件没有生效
`<body>
  <div id="app">
    <div class="flow">
      <super-flow></super-flow>
    </div>
  </div>

  
  <script src="./static/lib/index.umd.min.js"></script>
  <script>
    var vm = new Vue({
      el: '#app',
      component: { SuperFrom },
    })
  </script>
</body>`

**Comment by MingMingDa** [comment]
为什么我引入之后组件好像没有生效
```
<body>
  <div id="app">
    <div class="flow">
      <super-flow></super-flow>
    </div>
  </div>

  <!-- flow -->
  <script src="./static/lib/index.umd.min.js"></script>
  <link rel="stylesheet" href="./static/lib/index.css">
  <script>
    var vm = new Vue({
      el: '#app',
      component: { SuperFrom },
    })
  </script>
</body>
```
