### ISSUE TITLE
node增加点击事件

### ISSUE THREAD

**Issue by xiaoyangdian** [caohuatao/vue-super-flow#95]
![image](https://github.com/caohuatao/vue-super-flow/assets/42017441/cf582482-ac77-4e7a-a9b6-28618c84b6a4)
![image](https://github.com/caohuatao/vue-super-flow/assets/42017441/979dba2b-2ce0-4e5b-a8d4-ac5311f18c5a)

不多加点事件吗?想做点击弹窗都没辙..

**Comment by caohuatao** [comment]
插槽插入 node 上绑定。
